### ISSUE TITLE
button height changing with screen height is unintuitive

### ISSUE THREAD

**Issue by Chandram-Dutta** [opxica/modular-ui#27]
button height should't change with screen height. haven't seen material-tailwind or shadui doing it. button width factor makes sense. it would be great to have it constant or let the dev give height/width just like other flutter widget or let the button depend on its parent(how flutter does it now)

**Comment by Strange-Philip** [comment]
hello, can i work on this?😊

**Comment by Utkarsh4517** [comment]
Currently the height doesn't changes by default, because currently the `heightFactorPressed` and `heightFactorUnpressed` are same by default but a user can tweak that if they needed to. 
And yeah definitely a user can provide `heightFacorPressed` and `heightFactorUnpressed` explicitly to change the height of the button.

if both the values are same then button will not animate vertically.

Thoughts?

**Comment by Strange-Philip** [comment]
oh yeah, exactly... i guess we should leave it as it is

**Comment by Utkarsh4517** [comment]
What's your take on this @Chandram-Dutta ?
